Added CSS for SignUp and Homepage
Dufuna-CodeCamp/Dufuna-CodeCamp19 pull request #116
Opened 2019-11-28 21:11 UTC by Lumi007

### Task: CSS task for SignUp and Creation of Homepage

I worked on the CSS for the signup page
I created the homepage for my E-commerce page

2019-12-07 10:36 UTC, kenny-wealth requested changes

2019-12-07 10:36 UTC, kenny-wealth commented on submissions/olumidefakorede/HTML/hello.html
> +<!DOCTYPE html>
Did you plan to submit this?

2019-12-07 10:36 UTC, kenny-wealth commented on submissions/olumidefakorede/HTML/Signup Page.html
>  	<head>
Remove spaces in file names

2019-12-18 01:54 UTC, Lumi007 commented on submissions/olumidefakorede/HTML/Signup Page.html
>  	<head>
I have made the corrections

2019-12-18 17:35 UTC, kenny-wealth commented on submissions/olumidefakorede/HTML/js/script.js
> +        "image" : "",
Why are these empty?

2019-12-18 17:37 UTC, kenny-wealth commented on submissions/olumidefakorede/HTML/js/script.js
> +                ${Products[i].price}
Does this script work as expected? `products[i]` instead of `Products[i]` I think

2019-12-18 17:40 UTC, kenny-wealth commented on submissions/olumidefakorede/HTML/contactus.html
> +<!DOCTYPE html>
Seems there is `contact-us.html` and `contactus.html` on this PR. Please choose one

2020-02-12 19:28 UTC, closed without merging