Javascript
Dufuna-CodeCamp/Dufuna-CodeCamp19 pull request #136
Opened 2019-12-27 10:58 UTC by abolayo

i linked my landing page to a product page
i populate the product page using javascript

2020-01-06 17:57 UTC, taiwo-ladipo requested changes
A lot of files from previous tasks were duplicated in this pull request. Please focus solely on the javascript task i.e loading products dynamically. Also, ensure the products are styled like an e-commerce site's products

2020-01-06 17:57 UTC, taiwo-ladipo commented on submissions/medinatapanpa/javascript/dufuna.html
> +<!DOCTYPE html>
Can you rename this file to convey what it does e.g registration?

2020-01-06 17:57 UTC, taiwo-ladipo commented on submissions/medinatapanpa/javascript/js/nigerian.js
> +let nigerian = [
Please use a descriptive variable name

2020-01-06 17:58 UTC, taiwo-ladipo commented
It is not a good idea to delete files from previous task(s). Please revert

2020-01-12 19:18 UTC, abolayo commented
please how do I revert the deleted files? but the files are not supposed to be part of this PR.
 how do I solve the conflict issue?

2020-01-15 23:30 UTC, tegaphilip commented
> please how do I revert the deleted files? but the files are not supposed to be part of this PR.
> how do I solve the conflict issue?

@abolayo you need to do a revert to the last commit before you mistakenly deleted the files. or do a reset back to a previous commit. See https://code.likeagirl.io/how-to-undo-the-last-commit-393e7db2840b

if you need further help, ping me on slack, preferably from 9pm upwards or during the weekends.

2020-02-04 07:34 UTC, closed without merging