Javascript
Dufuna-CodeCamp/Dufuna-CodeCamp19 pull request #142
Opened 2020-01-14 03:20 UTC by joymeetme

### Task: <task name here>

I <clear and concise explanation>
I <clear and concise explanation>

2020-01-14 03:22 UTC, joymeetme commented
i added my javascript Task

2020-01-14 22:36 UTC, tegaphilip commented on submissions/ayodeleayobami/javascript/product.js
> +          product =
you need to declare the variable `product` here. e.g. `var product`. you can also declare it outside the loop. also the lines from `<div class ...` to `</div>` should be wrapped as a string before you can assign to the variable `product`.  Make sure to test properly

See

2020-01-14 22:36 UTC, tegaphilip commented on submissions/ayodeleayobami/javascript/product.js
> +            <div class="product image">
class should be `product-image`

2020-01-14 22:38 UTC, tegaphilip commented on submissions/ayodeleayobami/javascript/product.html
> +			<div class="product-content">
according to the task, these items should not be there until the button is clicked please check the task again and confirm. i am assuming that when you load the page, you don't see any products until the button is clicked.

2020-02-11 12:11 UTC, beccadaniel requested changes

2020-02-11 12:11 UTC, beccadaniel commented on submissions/ayodeleayobami/javascript/product.css
> +{
Hello @joymeetme Can you refactor this file as a whole and ensure it is well indented? The indentations are a bit off.

2020-02-11 12:28 UTC, merged