my sql database task
Dufuna-CodeCamp/Dufuna-CodeCamp19 pull request #165
Opened 2020-03-08 22:02 UTC by hummingbed

### Task: <task name here>

I <clear and concise explanation>
I <clear and concise explanation>

2020-03-10 09:24 UTC, hummingbed commented
my php database task

2020-03-12 13:41 UTC, ndanni commented
Kindly rename this Pull request to PHP task please.

2020-03-14 13:36 UTC, hummingbed commented
I just renamed to PHP Task as requested

2020-03-24 20:57 UTC, adaugochi commented on submissions/testfile.txt
> +this is a test file
What's this file for? Please remove it when not in use

2020-03-24 20:57 UTC, adaugochi commented on submissions/.gitignore
You aren't supposed to push this file. Please revert the changes made here

2020-03-24 20:57 UTC, adaugochi commented on submissions/MichaelMenebraye/PHP_Task/Input_Dashboard.php
> +    ';
No closing `</tr>` tag

2020-03-25 08:53 UTC, beccadaniel requested changes
Add the README.md file back. You don't have to make any changes to this particular file.

2020-03-25 09:05 UTC, hummingbed commented
Noted, comments effected

On Wed, Mar 25, 2020, 9:53 AM Folashade <notifications@github.com> wrote:

> *@beccadaniel* requested changes on this pull request.
>
> Add the README.md file back. You don't have to make any changes to this
> particular file.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp19/pull/165#pullrequestreview-380953711>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANMYUFW2CJ4JDEJF7WNMXA3RJHBAZANCNFSM4LD5KBMA>
> .
>

2020-03-27 09:57 UTC, adaugochi approved these changes

2020-03-27 10:54 UTC, beccadaniel approved these changes

2020-03-27 10:54 UTC, merged