I added a folder containing solution to task on php
Dufuna-CodeCamp/Dufuna-CodeCamp19 pull request #171
Opened 2020-03-15 15:34 UTC by Ireti203

### Task: <task name here>

I <clear and concise explanation>
I <clear and concise explanation>

2020-03-17 16:19 UTC, kehindemary approved these changes

2020-03-17 16:21 UTC, kehindemary submitted a review, later dismissed

2020-03-18 17:48 UTC, adaugochi commented
Well done @Ireti203 . Can you please change from folder name from `intro-php` to just `php`

2020-03-19 14:31 UTC, kenny-wealth requested changes

2020-03-19 14:31 UTC, kenny-wealth commented on submissions/OpemipoBanso/HTML/Untitled-1.txt
> +</php>
please undo if this is not needed

2020-03-19 14:31 UTC, kenny-wealth commented on submissions/IRETIOGEDENGBE/php-intro
> +
remove empty file

2020-03-19 14:31 UTC, kenny-wealth commented on submissions/IRETIOGEDENGBE/intro-php/sample.sql
> +DROP DATABASE addProducts;
Please fix indentations in this file. You could name this `setup.sql`

2020-03-19 14:31 UTC, kenny-wealth commented on submissions/IRETIOGEDENGBE/intro-php/sample.sql
> +DROP DATABASE addProducts;
Conventionally, you don't want to name your database `addProducts`. Names are nouns, `addProducts` is a verb... 
Can you rename your database to reflect this

2020-03-19 14:31 UTC, kenny-wealth commented on submissions/IRETIOGEDENGBE/css/signuppage.css
>  }
is this related to this pr in any way?

2020-03-19 14:31 UTC, kenny-wealth commented on submissions/IRETIOGEDENGBE/intro-php/create.php
> +<?php
Generally, fix indentations across all files. There is a shortcut to do this. You can refer to Slack #general channel.

2020-03-19 14:31 UTC, kenny-wealth commented on submissions/IRETIOGEDENGBE/intro-php/create.php
> +    $stmt_brands = $connect->query( 'SELECT * FROM addProducts.brands' );
since `configure.php` is imported into this file and that was used to set up the db connection, you should remove the database names from the queries.

2020-03-19 14:31 UTC, kenny-wealth commented on submissions/IRETIOGEDENGBE/intro-php/create.php
> +            ':'.implode( ', :', array_keys( $newProduct ) )
I'm not sure what is going on here, please explain

2020-03-24 20:59 UTC, adaugochi commented on submissions/IRETIOGEDENGBE/intro-php/sample.sql
> +
remove whitespace

2020-03-24 20:59 UTC, adaugochi commented on submissions/IRETIOGEDENGBE/php-intro
> +
Remove file, if not in use

2020-03-24 20:59 UTC, adaugochi commented on submissions/IRETIOGEDENGBE/intro-php/overview.php
> +<td><?php echo escape( $row['id'] );
code line 32 to 40 are not properly formatted

2020-03-24 20:59 UTC, adaugochi commented on submissions/IRETIOGEDENGBE/intro-php/create.php
> +    <button><a href = 'overview.php'>view products in database</a>
I think `View Products` is better than `view products in database`

2020-03-24 20:59 UTC, adaugochi commented on submissions/IRETIOGEDENGBE/intro-php/overview.php
> +<a href = 'create.php'>Back to database</a>
This is confusing `back to database` can you say `Add new product`

2020-03-26 13:28 UTC, closed without merging