Updated_CSS_Task
Dufuna-CodeCamp/Dufuna-CodeCamp19 pull request #66
Opened 2019-11-05 02:36 UTC by Chigoz169

### Task: <CSS Task>

 My previous work was removed because i used inline CSS styling method.
 I have updated it by adding an external CSS style method and also modified my original HTML file 
 which was previously sent.

2019-11-07 18:03 UTC, kenny-wealth commented on submissions/AbrahamJudah/HTML/SignUp.html
> +            <img src="vmart-logo.png" id="image" alt="logo" width="80" height="40" > <h1  class="header" >VivaMart</h1>
You need to push this picture, and include it this PR.
Also fix indentation on this line

2019-11-07 18:03 UTC, kenny-wealth commented on submissions/AbrahamJudah/HTML/SignUp.html
> +<!DOCTYPE html>
Page looks good. Nice work!

2019-11-07 18:11 UTC, kenny-wealth commented on submissions/AbrahamJudah/HTML/styles.css
> +    margin-left: 300px;
Try `margin:auto` to automatically center the registration wrapper. So you won't have to specify margin-left and margin-right

2019-11-28 20:43 UTC, taiwo-ladipo requested changes

2019-11-28 20:43 UTC, taiwo-ladipo commented on submissions/AbrahamJudah/HTML&CSS/SignUp.html
> +                <label for="first name" class="registration-label">First Name</label>
Well done Chigozie
Attribute values like name, id, etc., should not have spaces. You can separate words with a hyphen or underscore. Please fix all ocurrences

2019-11-28 20:43 UTC, taiwo-ladipo commented on submissions/AbrahamJudah/HTML&CSS/SignUp.html
> +<html lang="en">
Please add a link to this page on the home page

2019-11-28 20:43 UTC, taiwo-ladipo commented on submissions/AbrahamJudah/HTML&CSS/VivaMart.html
> +                <i class="fas fa-list "></i> &nbsp;Categories
I see a lot of FontAwesome icon usage in your code but I don't see the icons on the page. Can you make them show?

2019-11-28 20:43 UTC, taiwo-ladipo commented on submissions/AbrahamJudah/HTML&CSS/styler.css
> +    display: inline-block;
You can use a single class definition for all the _p_s here to avoid repetition

2019-11-28 20:43 UTC, taiwo-ladipo commented on submissions/AbrahamJudah/HTML&CSS/styler.css
> + .deal3 a {
Use a single class definition here as well

2019-11-28 20:43 UTC, taiwo-ladipo commented on submissions/AbrahamJudah/HTML&CSS/styler.css
> +
Please clear empty lines

2019-11-28 20:43 UTC, taiwo-ladipo commented on submissions/AbrahamJudah/HTML&CSS/styles.css
> +body {
This file's name is similar to the other stylesheet. Please rename the file after the page it styles

2019-11-29 19:59 UTC, taiwo-ladipo approved these changes

2019-12-05 18:05 UTC, kunmi02 approved these changes

2019-12-07 10:27 UTC, merged