Corrected Konga Page files format, HTML assignment
Dufuna-CodeCamp/Dufuna-CodeCamp19 pull request #79
Opened 2019-11-10 01:07 UTC by akoladepaul

Corrected Konga Page files format, HTML assignment and a current state of CSS project and e-commerce project.

### Task: <task name here>

I <clear and concise explanation>
I <clear and concise explanation>

2019-11-11 14:00 UTC, kenny-wealth requested changes

2019-11-11 14:00 UTC, kenny-wealth commented on Paul_Akolade/HTML/Html Form Elements.txt
> +QUESTION 1
Remove spaces in file name. Also state specifically what Task this is

2019-11-11 14:00 UTC, kenny-wealth commented on Paul_Akolade/Design Konga Reg Page/css/login.css
> +/*
Please remove spaces in folder names

2019-11-11 14:00 UTC, kenny-wealth commented on Paul_Akolade/CSS/README.md
> +# dufuna_codecamp
Please move all your folders into the submissions folder

2019-11-11 14:00 UTC, kenny-wealth commented on Paul_Akolade/Design Konga Reg Page/login.html
> +<!DOCTYPE html>
Page looks good 👍

2019-11-14 13:45 UTC, akoladepaul commented on Paul_Akolade/CSS/README.md
> +# dufuna_codecamp
Please i don't fully understand you. As regards moving all folders to submissions folder.
As at now all my folders are in paul_akolade folder which is then in the submissions folder.

2020-03-03 13:01 UTC, ndanni commented
Kindly move your Tasks to the submissions folder.

2020-03-03 13:01 UTC, closed without merging

2020-03-03 13:03 UTC, ndanni commented
Kindly move your task to the submissions folder. Your PR will be approved once that is done.