uxDesign task
Dufuna-CodeCamp/Dufuna-CodeCamp19 pull request #94
Opened 2019-11-13 15:00 UTC by Heedharyhart

I closed all my PR and taking the submission from the beginning due to alot of conflict my github is experiencing

2019-11-20 22:12 UTC, Heedharyhart commented
these has not been merged

2019-11-23 09:37 UTC, kenny-wealth requested changes

2019-11-23 09:37 UTC, kenny-wealth commented on submissions/Abdulkareem Idayat Olaide
> +
You may delete this file if not needed.

2019-11-23 09:37 UTC, kenny-wealth commented on uxDesign
> +
Delete this if not needed

2019-11-24 19:11 UTC, Heedharyhart commented
Pls, how do i delete it???? Have tried it, but is not working

On Sat, Nov 23, 2019, 10:37 AM Kehinde Ladipo <notifications@github.com>
wrote:

> *@kenny-wealth* requested changes on this pull request.
> ------------------------------
>
> In submissions/Abdulkareem Idayat Olaide
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp19/pull/94#discussion_r349865996>
> :
>
> > @@ -0,0 +1 @@
> +
>
> You may delete this file if not needed.
> ------------------------------
>
> In uxDesign
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp19/pull/94#discussion_r349866006>
> :
>
> > @@ -0,0 +1 @@
> +
>
> Delete this if not needed
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp19/pull/94?email_source=notifications&email_token=AM6FQDRS4BLX3RT7TDO7X2DQVD2W3A5CNFSM4JM4WUVKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCMX5SFI#pullrequestreview-321902869>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM6FQDRL5CAQ5LRVHXQPKB3QVD2W3ANCNFSM4JM4WUVA>
> .
>

2019-11-24 19:15 UTC, tegaphilip commented
@Heedharyhart delete from your computer. then do a `git add`, `git commit -m 'message'` and a `git push origin master`

2019-11-24 19:58 UTC, Heedharyhart commented
Alright
Thanks sir

On Sun, Nov 24, 2019, 8:15 PM Tega <notifications@github.com> wrote:

> @Heedharyhart <https://github.com/Heedharyhart> delete from your
> computer. then do a git add, git commit -m 'message' and a git push
> origin master
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp19/pull/94?email_source=notifications&email_token=AM6FQDT3E7H2AP2YQQKSO3DQVLHDVA5CNFSM4JM4WUVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFASTAQ#issuecomment-557918594>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM6FQDVG6DA7UJUS346ILWDQVLHDVANCNFSM4JM4WUVA>
> .
>

2020-02-12 13:25 UTC, closed without merging