Landing
Dufuna-CodeCamp/Dufuna-CodeCamp19 pull request #99
Opened 2019-11-16 12:16 UTC by abolayo

i added my landing page
i added herbals.css file
i added two image files

2019-11-17 09:54 UTC, kenny-wealth commented
Please give the PR a more descriptive title

2019-11-17 10:02 UTC, kenny-wealth requested changes

2019-11-17 10:02 UTC, kenny-wealth commented on submissions/medinatapanpa/homepage2/index.html
> +                        <img class="logo"src="pistachios.jpg" alt="herbs" class= "pics">
`pistachios.jpg` was not checked in

2019-11-17 10:02 UTC, kenny-wealth commented on submissions/medinatapanpa/homepage2/index.html
> +    <footer>
Footer is part of the body section

2019-11-17 10:02 UTC, kenny-wealth commented on submissions/medinatapanpa/homepage2/index.html
> +<!doctype html>
Generally review indentations using the Styleguide provided

2019-11-17 10:02 UTC, kenny-wealth commented on submissions/medinatapanpa/homepage2/herbal.css
> +.topnav {
Please remove if it's not needed

2019-11-19 14:01 UTC, abolayo commented on submissions/medinatapanpa/homepage2/index.html
> +                        <img class="logo"src="pistachios.jpg" alt="herbs" class= "pics">
Resolved

2019-11-19 14:02 UTC, abolayo commented on submissions/medinatapanpa/homepage2/index.html
> +    <footer>
Noted

2019-11-19 14:02 UTC, abolayo commented on submissions/medinatapanpa/homepage2/herbal.css
> +.topnav {
Done

2019-11-21 18:37 UTC, kunmi02 commented
> i added my landing page
> i added herbals.css file
> i added two image files

2019-11-21 18:37 UTC, closed without merging